### ISSUE TITLE
Undelete function

### ISSUE THREAD

**Issue by jdittrich** [jdittrich/quickMockup#12]
**Story:** As a user, I want to recover from errors from e.g. accidental input or so. 

**Possible implementation:** An "undelete" button aside of the delete button which restores the most recently delete object.

**Brief context:** A full undo/redo would be great, but it is not in the scope and the technology the project is based on (basically supercharged HTML) would make it rather difficult anyway.

What would cover the most likely error source imho is an un-delete function that restores the most recently delete object. It would not offer a history-like function, but more a oops-I-did-not intent-to-press-this recovery. 

To do: (e.g. via comments)
- [x] possible implementation concept: [Detach](http://api.jquery.com/detach/) the element and store it in a variable. 
- [x] Is that a decent idea?
- [x] Can we just remember the object we detached from and reattach if needed or is it more complicated?  (I first thought of the former parent object being deleted is a fail case, but in this case that object would be our recently-deleted one now)
- [x] Hmm, building it :-)

**Comment by jdittrich** [comment]
#6 – [delete shortcut on a mac](https://github.com/jdittrich/quickMockup/issues/6) is also a delete related-issue.

**Comment by simonv3** [comment]
Yeah this would be nice functionality to have. I think what you outline makes sense if we're not going to store all of the state of this app (undo is such a nightmare).

**Comment by jdittrich** [comment]
please try (demopage). Currently, I have not bound a shortcut (only button click for now) but that should be no problem to do later.

**Comment by jdittrich** [comment]
shortcut added too. closing this.

**Comment by simonv3** [comment]
Gonna make a quick edit on this for mac users.
