### ISSUE TITLE
Link in Markdown should not be clickable

### ISSUE THREAD

**Issue by jdittrich** [jdittrich/quickMockup#17]
When you create a link in Markdown (`[link](www.example.com)`) it is clickable in the mockup. It should not be, since it leads to an attempt to change the page.

**Comment by simonv3** [comment]
Though, having it be clickable allows for states.

**Comment by paulproteus** [comment]
One pattern I like here, if possible, is what Google Docs does for links:

![anim](https://cloud.githubusercontent.com/assets/25457/12427029/dd7d72d2-beaa-11e5-82d7-a6ce243e1bf0.gif)

**Comment by paulproteus** [comment]
In this proposal, the link doesn't directly navigate you away from the app, but creates a mini pop-up that explains that you _can_ navigate the page if you want.

**Comment by paulproteus** [comment]
Just one option; and let me know if I should pipe down with my random suggestions.

**Comment by simonv3** [comment]
I had no idea example.com actually went somewhere.

**Comment by jdittrich** [comment]
States are not in scope, imho:
1. My experience is that such a thing would call for a MVC or otherwise architectural more advances solution
2. I'm rather happy if all the mockup-ing works fine (which makes the approach much like Balsamiq’s, which only covers mockups without interactivity)

Does that make sense?

What I could imagine to be fruitful regarding scope and technology is having simple scroll-to links. At this positions one could naturally put a different state. So you could e.g. scroll and look at them, but also click through and it would scroll to the position where the "next" part is placed. 

_If you use quickMockup and note that you need the linking/scroll-linking feature, we can rename this bug OR start a new one_

**Comment by simonv3** [comment]
That's fair.

**Comment by jdittrich** [comment]
@paulproteus  

> let me know if I should pipe down with my random suggestions.

No problem, suggestions are welcome.

**Comment by paulproteus** [comment]
Y'all are very kind!

Y'all are also shockingly effective. It's a joy to watch this project move
forward.
