### ISSUE TITLE
read files from disk

### ISSUE THREAD

**Issue by jdittrich** [jdittrich/quickMockup#26]
**User Story:** I want to edit files I saved/got send

**How would this look like:** The user would have a button "load". After a click, a (upload) file chooser appears, a file can be selected. Its content is loaded. 

We might want to have a warning before, so the user can save any work before the new content is loaded. 

_Special case:_ the file is not a quickMockup file (or does not share its structure). In this case you get an error.

**Comment by jdittrich** [comment]
**Implementation**: 
- Use [File Reader API](http://www.html5rocks.com/en/tutorials/file/dndfiles/)*:
  - use FileReader.readAsText and inject in the container. 
- Check File structure:\* (Not essential)

**Comment by simonv3** [comment]
So I was thinking about a similar user story:

I was using my local quickMockup copy before updating to the most recent version and realized that if I update the code, and press refresh, I would lose all of my work, missing out on new functionality. There should probably be some way to import data (eg, reading a file) from an older version.

This lead to me to think that it might make sense to "save" data temporarily in the user's browser's cache? Then a refresh of the page would not delete their work.

**Comment by jdittrich** [comment]
The current version has the possibility to open files – did that work for you?
