### ISSUE TITLE
Empty group

### ISSUE THREAD

**Issue by simonv3** [jdittrich/quickMockup#33]
Would it be a good idea to have an empty group object to make it easier to manipulate some items that go together but don't necessarily fit "inside" of each other. This is what I was trying to achieve with "clearrect" in the file I uploaded in one of the other issues, where clearrect was just a thinly styled object.

**Comment by jdittrich** [comment]
The clearrect is a good idea; I would avoid creating concepts like empty groups (as long as I don't find a good way to make them easy to use) since this introduces group/ungroup issues which makes UI design in most applications rather annoying imho.

**Comment by jdittrich** [comment]
If you find out what kills the "clearrect" element's styles on loading the file, we could include this

**Comment by SlimerDude** [comment]
+1 for an empty group / clear rect. It could have an on-hover style so you can see it when dragging things around / moving the mouse. But then becomes invisible when viewing / printing.
