### ISSUE TITLE
Save editable version without file

### ISSUE THREAD

**Issue by jdittrich** [jdittrich/quickMockup#4]
User Story: …I need to save/share my work when I have no access to a file system (e.g. on mobile devices)
Possible Implementations: 
- Save to Server: Just save the HTML to a server
- Save to local storage

To be considered: 
- The HTML to be saved is quite cluttered/big. Thats o.k./to be expected since the tool is based on pure HTML and does not have a data abstraction layer. However, it may take too much space?  (?)
- Is the local storage synced between devices?

**Comment by jdittrich** [comment]
related: #3

**Comment by peterbrinck** [comment]
What about saving the mockup as PNG/JPG/PDF?

**Comment by jdittrich** [comment]
@peterbrinck, thanks for the suggestion!

I think existing functions (DevTool, AddOns, Screenshot…) do this fairly well already, so I would for now leave this to these already existing functions. 

Also, I thought of  editable saving. According to the issue name your idea is totally valid, so I'd need to clarify that.

**Comment by jdittrich** [comment]
What about API-posting the HTML/CSS to code pen or any other code sharing-with-display function?
Ideally, we could as well trigger a full-page (no code) view as well.

**Comment by peterbrinck** [comment]
It would be really great with a Save to Codepen feature!!

**Comment by jdittrich** [comment]
save to codepen works.
