### ISSUE TITLE
official Docker image

### ISSUE THREAD

**Issue by alexanderadam** [jdittrich/quickMockup#45]
Hi Jan,

it would be wonderful if there would be an [official Docker image on Dockerhub](https://hub.docker.com/search?q=quickMockup&type=image) for an easy and fast installation.

**Comment by jdittrich** [comment]
Hi @alexanderadam thanks for the suggestion. Since the quickMockup consists just of the files in the repo and does not have any runtime dependencies (no PHP, no Node, nor any extensions or config…) I think a docker image would not help a lot. If one wants to do some sort of mass deployment, a script to download and unpack the files might be a solution.

**Comment by alexanderadam** [comment]
IMHO a docker image helps to have an easy solution just to run things without having to think about what is required or not. It just runs. No setting up a webserver and putting the data in a particular folder or something complicated. Just `docker run quickmockup` and everything would be there.

I also don't think it is only useful when someone wants to do "mass deployment". People nowadays are even having Docker only infrastructures (see alone operating systems like RancherOS, CoreOS or RedHat Project Atomic).
Meaning, if they want to have quickMockup hosted on their infrastructure, they will have to create a Dockerfile anyway. And it is obviously better to have _one_ official image that is up to date, instead of a bunch of images that aren't up to date.
So having just static content is no reason _not_ to have a Docker container. It just makes the Dockerfile simpler than usual.
And Docker for static files is not unusual. There are [base images](https://hub.docker.com/r/halverneus/static-file-server/), [dedicated web servers](https://github.com/PierreZ/goStatic) (I don't see any sense in that though) and [tutorials](https://www.katacoda.com/courses/docker/create-nginx-static-web-server) if you are looking for it.
