### ISSUE TITLE
v2: Add strokes to elements

### ISSUE THREAD

**Issue by jdittrich** [jdittrich/quickMockup#50]
Story: Elements should have a stroke/outline/border (at least optionally)

![image](https://user-images.githubusercontent.com/3416487/70390227-644b5180-19c9-11ea-97cb-a2c7cba388c9.png)

Problem: Currently they don’t

Research so far: 
- Maybe we overwrote/blocked border by mixing in a composite for groupin gon drop?

**Comment by AlaaSarhan** [comment]
This is also solved now in current master. The strokes did not appear before as they did have a default white color that matched the background. `Window`, `Button` and `Container` elements have visible stroke now by default. `Text` has one too but it should probably not have one, so will remove it.
