### ISSUE TITLE
v2 visual representations of element in item collection bar. 

### ISSUE THREAD

**Issue by jdittrich** [jdittrich/quickMockup#58]
**Story:** If I search for a component I want to find it by its look

**Problem:** Currently people only see the name

**Solution:** 
* We could define a property that contains a link to an svg that represents the component
* We could render the graphics from draw2D directly into the component so the image gets automatically created.

**Comment by AlaaSarhan** [comment]
Doing some refactoring as part of this as well .. some things are starting to look like components, but gonna wait on introducing component framework for now as it is still quite simple case in general so far

**Comment by AlaaSarhan** [comment]
@jdittrich you can test my current attempt at solving this in branch `origin/58-visual-rep-in-toolbar` (PR #66)
