### ISSUE TITLE
Support images

### ISSUE THREAD

**Issue by frakman1** [jdittrich/quickMockup#71]
I wanted to mockup an existing website with some new design elements. 
So, I wanted to start with a screenshot of the existing website as a background image box and then add the mockup elements to it since that would make more sense that doing everything from scratch just to show the existing design and then adding the elements I want.
 
I see that there is an 'Image' box that I can drag in. It would be very helpful if that Image widget would allow me to upload my custom image onto it and move it around as needed.

**Comment by badcat** [comment]
@frakman1 As far as I understand, the "image" placeholder isn't really an image at all, so I'm guessing this will never work. However, the paragraph widget supports Markdown (MD). So, if your image is already available on the web, you could consider using the MD syntax to call an image into the paragraph element. Double click into the paragraph element and then it might look something like this:

`![Alt text](https://placeimg.com/640/480/any "a title")`

Which would preview as...

<img width="400" alt="markdown-image" src="https://user-images.githubusercontent.com/26096/203579465-d6813e74-5916-4424-a58c-99a364e5e6e6.png">

**Comment by frakman1** [comment]
That's a nice workaround. Thank you.
I'll try that out.
