### ISSUE TITLE
Table displayed like Markdown code

### ISSUE THREAD

**Issue by jdittrich** [jdittrich/quickMockup#9]
What happens: When I drag the table widget in, it appears as a text box with code-like text vaguely resembling a table. 
What is expected: It should look like the sketchy-style table in the widgets collection

**Comment by jdittrich** [comment]
Solution: There is whitespace in front of the lines of the table code, which triggers the "render as code" of Markdown. See, 

```
I am code with 4 spaces in front! I could be a table, too (but not with the spaces) 
```

We can just delete the spaces  from the table's "data-editable-content" attribute and we are fine.

**Comment by jdittrich** [comment]
fixed

**Comment by simonv3** [comment]
If whitespace breaks things, it's probably a good idea to strip user input as well?

**Comment by jdittrich** [comment]
It's just markdown and the "breaking" is actually having the 4 spaces which trigger <pre> mode, just like it should. I suppose that does not happen accidentally to users to type this – or did I misunderstand the idea?

**Comment by simonv3** [comment]
Nope, you're right, it's just a problem there!

**Comment by jdittrich** [comment]
great. so we leave it closed. Thanks for the remarks.
